apiVersion: v2
name: stock-service
description: A Helm chart for the Overly Serious Simple Stock Service
type: application
version: 0.1.0
appVersion: "1.0.0"
home: https://github.com/awsh-code/Overly-Serious-Simple-Stock-Service
sources:
  - https://github.com/awsh-code/Overly-Serious-Simple-Stock-Service
maintainers:
  - name: AWSH Code
    email: awsh@example.com
keywords:
  - stock
  - api
  - golang
  - microservice
  - circuit-breaker
  - caching
annotations:
  category: Applications
  licenses: MIT