{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stock-service.secretName" . }}
  labels:
    {{- include "stock-service.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.config.stockAPI.apiKey }}
  stock-api-key: {{ .Values.config.stockAPI.apiKey | b64enc | quote }}
  {{- else if .Values.secrets.data.stockApiKey }}
  stock-api-key: {{ .Values.secrets.data.stockApiKey | quote }}
  {{- else }}
  stock-api-key: ""
  {{- end }}
{{- end }}